=== FaKod/JDBCluster/xml/jdbcluster.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="cluster">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="select" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="class" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="id" type="xs:NMTOKEN" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="clustertype">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="cluster" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="privileges">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="UserPrivilegeChecker" minOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="UserPrivilegeChecker">
		<xs:complexType>
			<xs:attribute name="class" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="dao">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="property" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="class" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="id" type="xs:NMTOKEN" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="daotype">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="dao" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="jdbcluster">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="privileges" minOccurs="0"/>
				<xs:element ref="clustertype" minOccurs="0"/>
				<xs:element ref="daotype" minOccurs="0"/>
				<xs:element ref="domaindependancy" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="property">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="value"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:NMTOKEN" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="value">
		<xs:complexType mixed="true"/>
	</xs:element>
	<xs:element name="select">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="FilterClass" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="hql" type="xs:string" use="required"/>
			<xs:attribute name="id" type="xs:NMTOKEN" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="FilterClass">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="binding" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="class" type="xs:NMTOKEN" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="binding">
		<xs:complexType>
			<xs:attribute name="var" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="attribute" type="xs:NMTOKEN" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="domain">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="entry" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="domainid" type="xs:string" use="required"/>
			<xs:attribute name="domainlistclass" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="domaindependancy">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="domain" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="entry">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="valid" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="invalid" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="additionalmaster" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="value" type="xs:string"/>
			<xs:attribute name="slavedomainid" type="xs:string" use="required"/>
			<xs:attribute name="null">
				<xs:simpleType>
					<xs:restriction base="xs:boolean"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="invalid">
		<xs:complexType>
			<xs:attribute name="value" type="xs:string"/>
			<xs:attribute name="null">
				<xs:simpleType>
					<xs:restriction base="xs:boolean"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="all">
				<xs:simpleType>
					<xs:restriction base="xs:boolean"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="valid">
		<xs:complexType>
			<xs:attribute name="value" type="xs:string"/>
			<xs:attribute name="null">
				<xs:simpleType>
					<xs:restriction base="xs:boolean"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="all">
				<xs:simpleType>
					<xs:restriction base="xs:boolean"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="additionalmaster">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="additionalmaster" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="invalid" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="valid" minOccurs="0" maxOccurs="unbounded"/>	
			</xs:choice>
			<xs:attribute name="value"  type="xs:string" use="required"/>
			<xs:attribute name="masterdomainid"  type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== FaKod/JDBCluster/JDBCluster/xml/testDomainCheck.xml
<?xml version="1.0"?>
<jdbcluster xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="jdbcluster.xsd">
	<domaindependancy>
		<!-- check the Color amd ColorType Domains-->
		<domain domainid="ColorTypeDomain">
			<entry value="Color" slavedomainid="ColorDomain">
				<valid value="RED"/>
				<valid value="GREEN"/>
				<valid value="BLUE"/>
			</entry>
			<entry value="BlackWhite" slavedomainid="ColorDomain">
				<valid value="BLACK"/>
				<valid value="WHITE"/>
				<valid value="GREY50%"/>
			</entry>	
			<entry value="Unknown" slavedomainid="ColorDomain">
				<valid all="true" null="true"/>
			</entry>	
		</domain>
		<!--domain utcc 1-->
		<domain domainid="utcc">
			<entry value="COMBAT" slavedomainid="utacc">
				<valid value="AIRDEF"/>
				<valid value="AARMOR"/>
				<valid value="ARMANT"/>
				<valid value="ARMOUR"/>
			</entry>
			<entry value="COMSPT" slavedomainid="utacc">
				<valid value="ISFRCE"/>
				<valid value="ENG"/>
			</entry>
		</domain>
		<!--domain utacc 2-->
		<domain domainid="utacc">
			<entry value="AIRDEF" slavedomainid="utasc">
				<valid null="true"/>
				<valid value="ADCOMP"/>
				<valid value="ADGUN"/>
			</entry>
			<entry value="AARMOR" slavedomainid="utasc">
				<valid null="true"/>
			</entry>
		</domain>
		<!--domain utasc 3-->
		<domain domainid="utasc">
			<!-- values for null entry-->
			<entry null="true" slavedomainid="utssc">
				<valid all="true" null="true"/>
			</entry>
			<entry null="true" slavedomainid="utgmc">
				<valid all="true" null="true"/>
			</entry>
			<entry null="true" slavedomainid="utqc">
				<invalid value="CORPS"/>
				<invalid value="DIV"/>
				<invalid value="FORCE"/>
				<invalid value="HMAD"/>
			</entry>
			<!-- values fpr ADCOMP entry -->
			<entry value="ADCOMP" slavedomainid="utssc">
				<valid all="true" null="true"/>
			</entry>
			<entry value="ADCOMP" slavedomainid="utgmc">
				<valid all="true" null="true"/>
			</entry>
			<entry value="ADCOMP" slavedomainid="utqc">
				<invalid value="CORPS"/>
				<invalid value="DIV"/>
				<invalid value="FORCE"/>
			</entry>
		</domain>
	</domaindependancy>
</jdbcluster>

=== FaKod/JDBCluster/test/test/domain/jdbcluster.conf.xml
<?xml version="1.0" encoding="UTF-8"?>
<jdbcluster xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://jdbcluster.sourceforge.net/jdbcluster.xsd">
	<privileges>
		<UserPrivilegeChecker class="mycluster.privilege.UserPrivilege"/>
	</privileges>
	<!-- Definition of available Cluster Objects-->
	<clustertype>
		<!--configure cluster CAuto-->
		<cluster id="car" class="mycluster.CCar">
			<!--special filter "name" for cluster CAuto is available-->
			<!--select: ...where NAME=test.testfilter.NameFilter.getName()-->
			<select id="name" hql="NAME=:UNITNAME">
				<FilterClass class="test.testfilter.NameFilter">
					<binding var="UNITNAME" attribute="name"/>
				</FilterClass>
			</select>
			<!--select for coordinates-->
			<select id="position" hql="LATITUDE=:LAT and LONGITUDE=:LONG">
				<FilterClass class="test.testfilter.PositionFilter">
					<binding var="LONG" attribute="longitude"/>
					<binding var="LAT" attribute="latitude"/>
				</FilterClass>
			</select>
			<!--select only for LATITUDE-->
			<select id="positionLatOnly" hql="LATITUDE=:LATONLY">
				<FilterClass class="test.testfilter.PositionFilter">
					<binding var="LATONLY" attribute="latitude"/>
				</FilterClass>
			</select>
		</cluster>
		<!--configure cluster CFahrrad-->
		<cluster id="bicycle" class="mycluster.CBicycle"/>
	</clustertype>
	
	<!--confure available dao classes-->
	<daotype>
		<!--configure dao class Auto-->
		<dao id="Car" class="dao.Car">
			<!--sets parameter longitude to 1.234-->
			<property name="longitude">
				<value>1.234</value>
			</property>
			<!--sets parameter latitude to 5.678-->
			<property name="latitude">
				<value>5.678</value>
			</property>
			<!--sets parameter name to MyDefaultAutoName-->
			<property name="name">
				<value>MyDefaultAutoName</value>
			</property>
		</dao>
	</daotype>
	
	<!-- configure domain dependancies-->
	<!-- this Example is shown in CFahrrad...-->
	<domaindependancy>
		<!-- define all "not" masterdomains -->
		<domain domainid="ColorShadingDomain" domainlistclass="mycluster.domain.ColorShadingDomainList"/>
		<!-- define master domain "ColorTypeDomain"-->
		<domain domainid="ColorTypeDomain" domainlistclass="mycluster.domain.ColorTypeDomainList">
			<!-- define entries for slave domain "ColorDomain" -->
			<entry value="Color" slavedomainid="ColorDomain">
				<valid value="RED"/>
				<valid value="GREEN"/>
				<valid value="BLUE"/>
			</entry>
			<entry value="BlackWhite" slavedomainid="ColorDomain">
				<valid value="BLACK"/>
				<valid value="WHITE"/>
				<valid value="GREY50%"/>
			</entry>
			<entry value="None" slavedomainid="ColorDomain">
				<invalid all="true"/>
			</entry>
			<entry value="All" slavedomainid="ColorDomain">
				<valid all="true" null="true"/>
			</entry>
		</domain>
		<!-- define master domain "ColorDomain"-->
		<domain domainid="ColorDomain" domainlistclass="mycluster.domain.ColorDomainList">
			<!-- wildcard for all undefined master domain values-->
			<entry value="*" slavedomainid="ColorShadingDomain"/>
			<!-- except master domain value "RED" is checked -->
			<entry value="RED" slavedomainid="ColorShadingDomain">
				<valid value="LightRED"/>
				<valid value="DarkRED"/>
				<additionalmaster value="All" masterdomainid="ColorTypeDomain">
					<invalid value="LightRED"/>
					<valid value="MiddleRED"/>
				</additionalmaster>
			</entry>
		</domain>
	</domaindependancy>
</jdbcluster>

=== FaKod/JDBCluster/JDBCluster/test/test/domain/adddomain/DomainConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 

categoryCode		subCatCode		subSubCatCode		subSubSubCatCode		
[null]				[null]			[null]				[null]					
________________________________________________________________________________
A1					[null]			[any],[null]		[null]
					____________________________________________________________
					A2				[any],[null]		A4,[null]
					____________________________________________________________
					B2				A3,[null]			[any],[null]
________________________________________________________________________________
B1					[null]			[any],[null]		[null]							
					____________________________________________________________
					A2				[any],[null]		A4,[null]
					____________________________________________________________
					B2				B3,[null]			B4,[null]
					
 -->
<jdbcluster xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="jdbcluster.xsd">
	<privileges>
		<UserPrivilegeChecker class="UserPrivilege"/>
	</privileges>
	<clustertype>
		<cluster class="test.domain.adddomain.AddDomainCluster" id="AddDomainCluster"/>
	</clustertype>
	<domaindependancy>
		<domain domainid="categoryCode" domainlistclass="test.domain.adddomain.AddDomainList">
			<entry null="true" slavedomainid="subCatCode">
				<valid null="true"/>
			</entry>
			<entry value="A1" slavedomainid="subCatCode">
				<valid null="true"/>
				<valid value="A2"/>
				<valid value="B2"/>
			</entry>
			<entry value="B1" slavedomainid="subCatCode">
				<valid null="true"/>
				<valid value="A2"/>
				<valid value="B2"/>
			</entry>
		</domain>
		<domain domainid="subCatCode" domainlistclass="test.domain.adddomain.AddDomainList">
			<entry null="true" slavedomainid="subSubCatCode">
				<valid null="true"/>
				<additionalmaster value="A1" masterdomainid="categoryCode">
					<valid null="true" all="true"/>
				</additionalmaster>
				<additionalmaster value="B1" masterdomainid="categoryCode">
					<valid null="true" all="true"/>
				</additionalmaster>
			</entry>
			<entry value="A2" slavedomainid="subSubCatCode">
				<valid all="true" null="true"/>
			</entry>
			<entry value="B2" slavedomainid="subSubCatCode">
				<valid null="true"/>
				<additionalmaster value="A1" masterdomainid="categoryCode">
					<valid value="A3"/>
				</additionalmaster>
				<additionalmaster value="B1" masterdomainid="categoryCode">
					<valid value="B3"/>
				</additionalmaster>
			</entry>
		</domain>
		<domain domainid="subSubCatCode" domainlistclass="test.domain.adddomain.AddDomainList">
			<entry null="true" slavedomainid="subSubSubCatCode">
				<valid null="true"/>
				<additionalmaster value="A2" masterdomainid="subCatCode">
					<valid value="A4"/>
				</additionalmaster>
				<additionalmaster value="A1" masterdomainid="categoryCode">
					<additionalmaster value="B2" masterdomainid="subCatCode">
						<valid null="true" all="true"/>
					</additionalmaster>
				</additionalmaster>
				<additionalmaster value="B1" masterdomainid="categoryCode">
					<additionalmaster value="B2" masterdomainid="subCatCode">
						<valid value="B4"/>
					</additionalmaster>
				</additionalmaster>
			</entry>
			<entry value="A3" slavedomainid="subSubSubCatCode">
				<valid null="true"/>
				<additionalmaster value="A2" masterdomainid="subCatCode">
					<valid value="A4"/>
				</additionalmaster>
				<additionalmaster value="A1" masterdomainid="categoryCode">
					<additionalmaster value="B2" masterdomainid="subCatCode">
						<valid null="true" all="true"/>
					</additionalmaster>
				</additionalmaster>
			</entry>
			<entry value="B3" slavedomainid="subSubSubCatCode">
				<valid null="true"/>
				<additionalmaster value="A2" masterdomainid="subCatCode">
					<valid value="A4"/>
				</additionalmaster>
				<additionalmaster value="B1" masterdomainid="categoryCode">
					<additionalmaster value="B2" masterdomainid="subCatCode">
						<valid value="B4"/>
					</additionalmaster>
				</additionalmaster>
			</entry>
		</domain>
		<domain domainid="subSubSubCatCode" domainlistclass="test.domain.adddomain.AddDomainList"/>
	</domaindependancy>
</jdbcluster>
