=== FaKod/JDBCluster/JDBCluster/xml/jdbcluster.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
  <xs:element name="cluster">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="select" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="class" type="xs:NMTOKEN" use="required" />
      <xs:attribute name="id" type="xs:NMTOKEN" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="clustertype">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="cluster" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="dao">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="property" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="class" type="xs:NMTOKEN" use="required" />
      <xs:attribute name="id" type="xs:NMTOKEN" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="daotype">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="dao" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="jdbcluster">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="clustertype" />
        <xs:element ref="daotype" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="property">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="value" />
      </xs:sequence>
      <xs:attribute name="name" type="xs:NMTOKEN" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="value">
    <xs:complexType mixed="true" />
  </xs:element>
	
	<xs:element name="select">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="FilterClass" minOccurs="0" />
      </xs:sequence>
      <xs:attribute name="hql" type="xs:string" use="required" />
      <xs:attribute name="id" type="xs:NMTOKEN" use="required" />
    </xs:complexType>
  </xs:element>
	
	<xs:element name="FilterClass">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="binding" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="class" type="xs:NMTOKEN" use="required" />
    </xs:complexType>
  </xs:element>
	
	<xs:element name="binding">
    <xs:complexType>
      <xs:attribute name="var" type="xs:NMTOKEN" use="required" />
      <xs:attribute name="attribute" type="xs:NMTOKEN" use="required" />
    </xs:complexType>
  </xs:element>

</xs:schema>

=== FaKod/JDBCluster/JDBCluster/xml/jdbcluster.conf.xml
<?xml version="1.0" encoding="UTF-8"?>
<jdbcluster xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="jdbcluster.xsd">
	
	<!-- Definition of available Cluster Objects-->
	<clustertype>
		
		<!--configure cluster CAuto-->
		<cluster id="auto" class="mycluster.CAuto">
			
			<!--special filter "name" for cluster CAuto is available-->
			<!--select: ...where NAME=test.testfilter.NameFilter.getName()-->
			<select id="name" hql="NAME=:UNITNAME">
				<FilterClass class="test.testfilter.NameFilter">
					<binding var="UNITNAME" attribute="name"/>
				</FilterClass>
			</select>
			<!--select for coordinates-->
			<select id="position" hql="LATITUDE=:LAT and LONGITUDE=:LONG">
				<FilterClass class="test.testfilter.PositionFilter">
					<binding var="LONG" attribute="longitude"/>
					<binding var="LAT" attribute="latitude"/>
				</FilterClass>
			</select>
			<!--select only for LATITUDE-->
			<select id="positionLatOnly" hql="LATITUDE=:LATONLY">
				<FilterClass class="test.testfilter.PositionFilter">
					<binding var="LATONLY" attribute="latitude"/>
				</FilterClass>
			</select>
		</cluster>
		
		<!--configure cluster CFahrrad-->
		<cluster id="fahrrad" class="mycluster.CFahrrad"/>
		
	</clustertype>
	
	<!--confure available dao classes-->
	<daotype>
		
		<!--configure dao class Auto-->
		<dao id="Auto" class="dao.Auto">
			
			<!--sets parameter longitude to 1.234-->
			<property name="longitude">
				<value>1.234</value>
			</property>
			<!--sets parameter latitude to 5.678-->
			<property name="latitude">
				<value>5.678</value>
			</property>
			<!--sets parameter name to MyDefaultAutoName-->
			<property name="name">
				<value>MyDefaultAutoName</value>
			</property>
		</dao>
		
	</daotype>
	
</jdbcluster>
